# Generated by Django 5.2.7 on 2025-10-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0003_remove_businesscard_user_businesscard_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscard',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
